
name: Qiskitenv
dependencies:
- python==3.7.10
- pip
- matplotlib
- notebook
- ipywidgets
- pip:
  - qiskit
  - pylatexenc
  - git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src
  - numexpr
